#!/usr/bin/env python3
"""
export_embeddings.py
====================
Export pre-computed Quran embeddings for self-hosted Smart Search.

Reads the embedding cache generated by 01_build_pairs.py and produces
two compact binary files that the Vercel Smart Search API loads directly —
eliminating the need for Qdrant entirely.

Output (data/embeddings/):
  ar_emb.bin   — Arabic lemma embeddings  (float32, n × dims, ~19 MB)
  en_emb.bin   — English embeddings       (float32, n × dims, ~19 MB)
  meta.json    — ayah IDs, english texts, arabic texts

Usage:
  python scripts/export_embeddings.py

After running, commit data/embeddings/ and Vercel will serve Smart Search
using these local files instead of Qdrant.
"""

import argparse
import json
import sys
import pandas as pd
import numpy as np
from pathlib import Path

def _parse_args():
    p = argparse.ArgumentParser(description="Export pre-computed Quran embeddings to binary format.")
    p.add_argument("--cache-dir",  default=None, help="Directory containing q_ar_emb.npy / q_en_emb.npy (default: <repo-root>/data/cache)")
    p.add_argument("--output-dir", default=None, help="Destination for ar_emb.bin / en_emb.bin / meta.json (default: <repo-root>/data/embeddings)")
    p.add_argument("--raw-dir",    default=None, help="Directory containing raw Quran CSV files (default: <repo-root>/raw)")
    return p.parse_args()

_args = _parse_args()
SCRIPT_DIR = Path(__file__).parent
ROOT       = SCRIPT_DIR.parent
CACHE_DIR  = Path(_args.cache_dir)  if _args.cache_dir  else ROOT / "data" / "cache"
RAW_DIR    = Path(_args.raw_dir)    if _args.raw_dir    else ROOT / "raw"
OUT_DIR    = Path(_args.output_dir) if _args.output_dir else ROOT / "data" / "embeddings"
OUT_DIR.mkdir(exist_ok=True)

# ── Verify cache exists ──────────────────────────────────────────
for fname in ["q_ar_emb.npy", "q_en_emb.npy"]:
    if not (CACHE_DIR / fname).exists():
        print(f"ERROR: {CACHE_DIR / fname} not found.")
        print("Run 01_build_pairs.py first to generate the embedding cache.")
        sys.exit(1)

# ── Load cached embeddings ───────────────────────────────────────
print("Loading cached embeddings from data/cache/…")
ar_emb = np.load(CACHE_DIR / "q_ar_emb.npy").astype(np.float32)
en_emb = np.load(CACHE_DIR / "q_en_emb.npy").astype(np.float32)
print(f"  ar_emb: {ar_emb.shape}   en_emb: {en_emb.shape}")

if ar_emb.shape != en_emb.shape:
    print("ERROR: ar_emb and en_emb have different shapes — re-run 01_build_pairs.py.")
    sys.exit(1)

n, dims = ar_emb.shape

# ── Load Quran text in the same row order as the embeddings ─────
# 01_build_pairs.py builds the q DataFrame from q_ar merged with q_en,
# in CSV row order. We replicate that merge to get the matching ayah_ids.
print("Loading Quran CSVs to reconstruct ayah order…")

def first_path(*candidates):
    for p in candidates:
        if Path(p).exists():
            return p
    return candidates[0]

def read_csv(path):
    for enc in ["utf-8", "utf-8-sig", "latin1"]:
        try:
            return pd.read_csv(path, encoding=enc)
        except Exception:
            pass
    return pd.read_csv(path, engine="python")

def find_col(df, names):
    cols_lower = {c.lower(): c for c in df.columns}
    for n in names:
        if n.lower() in cols_lower:
            return cols_lower[n.lower()]
    return None

qar_path = first_path(RAW_DIR / "quran.csv",          ROOT / "quran.csv")
qen_path = first_path(RAW_DIR / "Quran_English.csv",  ROOT / "Quran_English.csv")

q_ar = read_csv(qar_path)
q_en = read_csv(qen_path)

ar_surah = find_col(q_ar, ["surah", "Surah"])
ar_ayah  = find_col(q_ar, ["ayah",  "Ayah",  "ayat", "Ayat"])
ar_text  = find_col(q_ar, ["arabic_text", "arabic", "uthmani", "simple", "text"])
en_surah = find_col(q_en, ["surah", "Surah"])
en_ayah  = find_col(q_en, ["ayah",  "Ayah",  "ayat", "Ayat"])
en_text  = find_col(q_en, ["english_text", "translation", "text", "english"])

q_ar["surah"]    = pd.to_numeric(q_ar[ar_surah], errors="coerce").astype(int)
q_ar["ayah"]     = pd.to_numeric(q_ar[ar_ayah],  errors="coerce").astype(int)
q_ar["ayah_id"]  = q_ar["surah"].astype(str) + ":" + q_ar["ayah"].astype(str)
q_ar["arabic"]   = q_ar[ar_text].astype(str)

q_en["surah"]    = pd.to_numeric(q_en[en_surah], errors="coerce").astype(int)
q_en["ayah"]     = pd.to_numeric(q_en[en_ayah],  errors="coerce").astype(int)
q_en["ayah_id"]  = q_en["surah"].astype(str) + ":" + q_en["ayah"].astype(str)
q_en["english"]  = q_en[en_text].astype(str)

q = q_ar[["ayah_id", "arabic"]].merge(
    q_en[["ayah_id", "english"]], on="ayah_id", how="left"
)
q["arabic"]  = q["arabic"].fillna("")
q["english"] = q["english"].fillna("")

if len(q) != n:
    print(f"ERROR: CSV has {len(q)} rows but embeddings have {n} rows.")
    print("Re-run 01_build_pairs.py with the same CSV files.")
    sys.exit(1)

print(f"  {n} ayat — CSV row order matches embedding order ✓")

# ── Export binary embedding files ────────────────────────────────
print("Exporting ar_emb.bin…")
ar_emb.tofile(str(OUT_DIR / "ar_emb.bin"))

print("Exporting en_emb.bin…")
en_emb.tofile(str(OUT_DIR / "en_emb.bin"))

# ── Export metadata ──────────────────────────────────────────────
print("Exporting meta.json…")
meta = {
    "dims": int(dims),
    "n":    int(n),
    "ids":  q["ayah_id"].tolist(),
    "en":   q["english"].tolist(),
    "ar":   q["arabic"].tolist(),
}
with open(OUT_DIR / "meta.json", "w", encoding="utf-8") as f:
    json.dump(meta, f, ensure_ascii=False, separators=(",", ":"))

# ── Summary ──────────────────────────────────────────────────────
ar_mb   = (OUT_DIR / "ar_emb.bin").stat().st_size / 1e6
en_mb   = (OUT_DIR / "en_emb.bin").stat().st_size / 1e6
meta_mb = (OUT_DIR / "meta.json").stat().st_size  / 1e6
print(f"\nExported to {OUT_DIR.relative_to(ROOT)}:")
print(f"  ar_emb.bin  {ar_mb:.1f} MB")
print(f"  en_emb.bin  {en_mb:.1f} MB")
print(f"  meta.json   {meta_mb:.1f} MB")
print(f"\nEmbed dims: {dims}  (model: paraphrase-multilingual-mpnet-base-v2)")
print("\nNext steps:")
print("  1. git add data/embeddings/")
print("  2. git commit -m 'data: add self-hosted Smart Search embeddings'")
print("  3. git push  → Vercel auto-deploys, Smart Search works without Qdrant")
