// POST /api/synthesize  { query, verses: [{ ref, text }] }
//
// Zero-hallucination synthesis:
// The LLM outputs ONLY a JSON structure — theme name + ordered list of verse refs.
// NO prose is generated by the LLM. All displayed text comes directly from the
// verse database on the client. The LLM cannot hallucinate content it never writes.
//
// Response: { theme: string, groups: [{ label: string, refs: string[] }], timing_ms }

const GROQ_API_KEY = process.env.GROQ_API_KEY;
const MODEL        = 'llama-3.1-8b-instant';
const MAX_TOKENS   = 800;
const TIMEOUT_MS   = 20000;

const SYSTEM_PROMPT = `You are a Quranic research assistant. Your ONLY job is to organize a list of verse references into thematic groups that answer the user's question.

OUTPUT FORMAT — return valid JSON only, no other text:
{
  "theme": "short answer title (max 8 words)",
  "groups": [
    { "label": "theme name", "refs": ["2:177", "3:92"] },
    { "label": "another theme", "refs": ["9:111"] }
  ]
}

RULES:
- Output ONLY the JSON object above. No prose, no explanation, no markdown.
- Each group label is 2-5 words describing what those verses share.
- Only include refs from the provided list — never invent or add refs.
- A verse may appear in only one group.
- Order groups from most to least relevant to the question.
- 2-6 groups maximum.`;

export default async function handler(req, res) {
  res.setHeader('Access-Control-Allow-Origin',  '*');
  res.setHeader('Access-Control-Allow-Methods', 'POST, OPTIONS');
  res.setHeader('Access-Control-Allow-Headers', 'Content-Type');
  if (req.method === 'OPTIONS') return res.status(204).end();
  if (req.method !== 'POST')   return res.status(405).json({ error: 'Method not allowed' });
  if (!GROQ_API_KEY)           return res.status(200).json({ groups: [], error: 'Missing GROQ_API_KEY' });

  let body = req.body;
  if (typeof body === 'string') { try { body = JSON.parse(body); } catch { body = {}; } }

  const query  = String(body?.query ?? '').trim().slice(0, 300);
  const verses = Array.isArray(body?.verses) ? body.verses.slice(0, 30) : [];

  if (!query || !verses.length) {
    return res.status(400).json({ error: 'Missing query or verses' });
  }

  const refList = verses
    .map(v => `[${v.ref}] ${String(v.text || '').slice(0, 80)}`)
    .join('\n');

  const userMessage = `Question: "${query}"\n\nVerses to organize:\n${refList}`;

  try {
    const t0   = Date.now();
    const resp = await Promise.race([
      fetch('https://api.groq.com/openai/v1/chat/completions', {
        method:  'POST',
        headers: {
          'Authorization': `Bearer ${GROQ_API_KEY}`,
          'Content-Type':  'application/json',
        },
        body: JSON.stringify({
          model:      MODEL,
          max_tokens: MAX_TOKENS,
          response_format: { type: 'json_object' },
          messages: [
            { role: 'system', content: SYSTEM_PROMPT },
            { role: 'user',   content: userMessage },
          ],
        }),
      }),
      new Promise((_, rej) => setTimeout(() => rej(new Error('timeout')), TIMEOUT_MS)),
    ]);

    if (!resp.ok) {
      const err = await resp.text();
      throw new Error(`Groq ${resp.status}: ${err.slice(0, 200)}`);
    }

    const data   = await resp.json();
    const raw    = (data?.choices?.[0]?.message?.content || '').trim();
    let parsed;
    try { parsed = JSON.parse(raw); } catch { throw new Error('Model returned invalid JSON'); }

    // Validate: only keep refs that were in the original list
    const validRefs = new Set(verses.map(v => v.ref));
    const groups = (parsed.groups || []).map(g => ({
      label: String(g.label || '').slice(0, 60),
      refs:  (g.refs || []).filter(r => validRefs.has(r)),
    })).filter(g => g.refs.length > 0);

    return res.status(200).json({
      theme:     String(parsed.theme || query).slice(0, 80),
      groups,
      timing_ms: Date.now() - t0,
    });

  } catch (e) {
    console.error('[synthesize] error:', e.message);
    return res.status(200).json({ theme: query, groups: [], error: e.message });
  }
}
